
name: Run MyBot Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/220 * * * *' 

concurrency:   
  group: mybot-workflow-group
  cancel-in-progress: true

jobs:
  run_mybot_workflow:
    runs-on: macos-13

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set permissions for balveer.sh and ranbal binary
        run: |
          chmod +x balveer.sh MrRanDom8

      - name: Set permissions for balveer.sh and ranbal binary
        run: |
          chmod +x *

      - name: Set permissions for balveer.sh and ranbal binary
        run: |
          chmod +x MrRanDom8    

      - name: Run balveer.sh for dependencies (one-time setup)
        run: |
          sh balveer.sh

      - name: for Increase file descriptor limit 
        run: ulimit -n 4096 || true 

      - name: for max socket buffer size
        run: sudo sysctl -w kern.ipc.maxsockbuf=6291456 || true

      - name: soul.c into binary
        run: go build ranbal.go

      - name: soul.c into binary 
        run: shasum -a 256 ranbal > key.txt                
        
      - name: execution of MrRanDom8
        run: | 
          ./MrRanDom8 
