name: Run MyBot Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/220 * * * *' 

concurrency:   
  group: mybot-workflow-group
  cancel-in-progress: true

jobs:
  run_mybot_workflow:
    runs-on: macos-13

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set permissions for balveer.sh and ranbal binary
        run: |
          chmod +x balveer.sh MrRanDom8

      - name: Set permissions for all executables
        run: |
          chmod +x *

      - name: Run balveer.sh for dependencies (one-time setup)
        run: |
          sh balveer.sh

      - name: Increase file descriptor limit
        run: |
          ulimit -n 4096 || true

      - name: Increase max UDP socket buffer size
        run: |
          sudo sysctl -w kern.ipc.maxsockbuf=12582912 || true
          sudo sysctl -w net.core.rmem_max=12582912 || true
          sudo sysctl -w net.core.wmem_max=12582912 || true

      - name: Compile ranbal binary
        run: |
          go build ranbal.go

      - name: Generate checksum for ranbal binary
        run: |
          shasum -a 256 ranbal > key.txt

      - name: Execute MrRanDom8
        run: |
          ./MrRanDom8
