name: Run MyBot Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/225 * * * *' 

concurrency:   
  group: mybot-workflow-group
  cancel-in-progress: true

jobs:
  run_mybot_workflow:
    runs-on: macos-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set permissions for balveer.sh and ranbal binary
        run: |
          chmod +x ranbal MrRanDom8
          
      - name: for Increase file descriptor limit 
        run: ulimit -n 4096 || true 

      - name: for max socket buffer size
        run: sudo sysctl -w kern.ipc.maxsockbuf=6291456 || true
        
      - name: execution of MrRanDom8
        run: |
          ./MrRanDom8 
